// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Icon:ic:baselineArrowRightAlt': typeof import('~icons/ic/baseline-arrow-right-alt')['default']
    'IconBi:exclamationCircleFill': typeof import('~icons/bi/exclamation-circle-fill')['default']
    'IconClarity:timesCircleSolid': typeof import('~icons/clarity/times-circle-solid')['default']
    'IconClarity:timesLine': typeof import('~icons/clarity/times-line')['default']
    'IconFaBrands:facebookF': typeof import('~icons/fa-brands/facebook-f')['default']
    'IconFaBrands:twitter': typeof import('~icons/fa-brands/twitter')['default']
    'IconFaBrands:youtube': typeof import('~icons/fa-brands/youtube')['default']
    'IconFaRegular:envelope': typeof import('~icons/fa-regular/envelope')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconFaSolid:envelope': typeof import('~icons/fa-solid/envelope')['default']
    'IconFaSolid:phoneAlt': typeof import('~icons/fa-solid/phone-alt')['default']
    'IconIc:baselineContentCopy': typeof import('~icons/ic/baseline-content-copy')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconMdi:checkCircle': typeof import('~icons/mdi/check-circle')['default']
    'IconMdi:chevronDown': typeof import('~icons/mdi/chevron-down')['default']
    'IconMdi:chevronUp': typeof import('~icons/mdi/chevron-up')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconPh:gear': typeof import('~icons/ph/gear')['default']
    'IconRi:facebookFill': typeof import('~icons/ri/facebook-fill')['default']
    'IconSimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
